[package]
name = "transtractor"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
lopdf = "0.38"
regex = "1.11.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8", features = ["v4"] }
once_cell = "1.19"